# Generated by Django 6.0 on 2025-12-05 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='Класс (например 1В)')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to=settings.AUTH_USER_MODEL, verbose_name='Классный руководитель')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('present_count_auto', models.PositiveIntegerField(default=0, verbose_name='Присутствуют (по списку)')),
                ('present_count_reported', models.PositiveIntegerField(verbose_name='Пришло по факту')),
                ('unexcused_absent_count', models.PositiveIntegerField(verbose_name='Неуважительные причины')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто ввёл данные')),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='attendance.classroom', verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Сводка посещаемости',
                'verbose_name_plural': 'Сводки посещаемости',
                'ordering': ['-date', 'class_room__name'],
                'unique_together': {('class_room', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО ученика')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='attendance.classroom', verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
                'ordering': ['class_room__name', 'full_name'],
                'unique_together': {('full_name', 'class_room')},
            },
        ),
        migrations.CreateModel(
            name='AbsentStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absent_students', to='attendance.attendancesummary', verbose_name='Сводка')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_records', to='attendance.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Отсутствующий ученик',
                'verbose_name_plural': 'Отсутствующие ученики',
                'unique_together': {('attendance', 'student')},
            },
        ),
    ]
