# Generated by Django 6.0 on 2025-12-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='student_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество учеников в классе'),
        ),
    ]
